### ISSUE TITLE
`acorn images -A` lists images only from the first project in `acorn projects`.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1185]
Server version - acorn version v0.5.1-5-g28a7873+28a78730

Steps to reproduce the problem:
Have few projects created with images in each of the projects. 
p1 - image1
p2 - image2

`acorn images -a` lists images only from the first project in `acorn projects`.
in the above case , only `image1` will be listed.

```
% acorn images -a -A
REPOSITORY   TAG       IMAGE-ID
<none>       <none>    d5bae66abc18
<none>       <none>    2c7ba01b4cc9

 % acorn projects
NAME           DEFAULT   DESCRIPTION
mynewproject             
acorn          *         
mytest2                  
test                     

% acorn images -a -j mynewproject 
REPOSITORY   TAG       IMAGE-ID
<none>       <none>    d5bae66abc18
<none>       <none>    2c7ba01b4cc9
 % acorn images -a -j acorn       
REPOSITORY                              TAG       IMAGE-ID
<none>                                  <none>    d5bae66abc18
<none>                                  <none>    371cd2fcba06
<none>                                  <none>    17f2d0dfba2e
<none>                                  <none>    ac725dc8ea46
<none>                                  <none>    b32144f8faa1
index.docker.io/sangeetha/mytestacorn   v0.0.2    d02d3c8d9a22
```

Also , In the output for ` acorn images -A ` , we should be able to show which project the images belong to  like `<project-name>/<image-id>`

**Comment by cjellick** [comment]
Based on out-of-band convo, this will probably get addressed holistically as part of the PR for project::resource. I'm going to move this issue back to "in progress" and it can be moved forward when that PR lands.

**Comment by cjellick** [comment]
moving out to v0.8.0

**Comment by cjellick** [comment]
We got rid of -A as a flag for `acorn images`. Its now just a command specific flag (i dont know all the commands that support it, but for `acorn ps` does)
