### ISSUE TITLE
acorn json output is not producing a json array

### ISSUE THREAD

**Issue by meldafrawi** [acorn-io/runtime#1272]
`acorn apps -o json` 

output: 
```
{
    "metadata": {
        "name": "withered-violet",
        "namespace": "acorn",
        "generation": 1,
        "creationTimestamp": "2023-02-27T21:55:06Z"
    },
...
}

{
    "metadata": {
        "name": "autumn-frog",
        "namespace": "acorn",
        "generation": 1,
        "creationTimestamp": "2023-02-26T03:43:15Z"
    },
....
}
```

**Comment by cjellick** [comment]
from @vincent99: 

Newline-delimeted JSON is at least a pseudo-standard, and arguably more useful for piping (you can't parse an array until the whole response is done)
..But an array is what most people would probably expect.  Should support both, -o json vs -o ndjson

Also, note: changing the default behavior would break the vscode plugin
