### ISSUE TITLE
Not able to have comma as part of secret value.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1325]
acorn version - acorn version v0.6.0+c6ffc99d

Steps to reproduce the problem:
Create secrets with values having ","
```
acorn secret create --data key1="a,b" testme
  ✗  ERROR:  invalid data format [b] must be in key=value form
```

Expected Behavior:
We should be allowed to create secrets with values having ",".

Note - we are allowed to use "," as part of secret values when creating secrets from Acornfile.

**Comment by g-linville** [comment]
You have to escape the quotes around the entire key-value pair in order for this to work:

```
❯ acorn secret create --data \"key1=a,b\" testme
testme

❯ a secret reveal testme
NAME      TYPE      KEY       VALUE
testme    opaque    key1      a,b
```

(Tested and working in both bash and fish.)

This is a limitation in Cobra itself. See this issue: https://github.com/spf13/pflag/issues/57

Moving to QA.

**Comment by sangee2004** [comment]
Able to create secrets successfully when  escaping the quotes as follows:

```acorn secret create --data \"key1=a,b\" testme```
