### ISSUE TITLE
No endpoint is made available when app is deployed with -p <port> option.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1353]
Server Version - `acorn version v0.6.0-36-g2df45d9f+2df45d9f`

Deploy app  -` acorn run -p 80`
```
args: {
	scale:   2
	new:     true
	oldtext: "old"
	newtext: "latest22"
}
containers: myweb: {
	image: "nginx"
	ports: "80"
	files: "/usr/share/nginx/html/index.html": std.ifelse(args.new, args.newtext, args.oldtext)
	memory: 102400K
	labels: key: "test-value"
}
```

No endpoint is made available for the app.

```
% acorn apps
NAME          IMAGE          HEALTHY   UP-TO-DATE   CREATED     ENDPOINTS                                                                          MESSAGE
misty-surf    357c130cbd19   1         1            5m13s ago                                                                                      OK
```

No endpoint is seen even when deploying apps with the above Acornfile using ` acorn run -p 80/http`

Note - If Acornfile has `ports: "80/http"` ,  launching app with  `acorn run -p 80` results in app getting deployed with `http://` endpoint.

**Comment by sangee2004** [comment]
Tested with acorn version-
    controllerImage: ghcr.io/acorn-io/acorn:v0.6.0-39-g87f8017e
    gitCommit: 87f8017e7b1146b6ce1753b42af3f84918f1a65b

Endpoints are still not being made available:

```
cat Acornfilep
args:{
 scale: 2
 new: true
 oldtext: "old"
 newtext: "latest22"
}
containers: {
   myweb: {
    image: "nginx"
    ports: "80"
    files: {
      "/usr/share/nginx/html/index.html": std.ifelse(args.new, args.newtext , args.oldtext)
    }
}
}

```
acorn run -n mytest1 -p 80  -f Acornfilep
acorn run -n mytest2 -p 80/http  -f Acornfilep
```

When no protocol is passed , load balancer is in pending state.
When  protocol is set as "http" in command line , there is no endpoint created.

```
% acorn apps    
NAME      IMAGE          HEALTHY   UP-TO-DATE   CREATED    ENDPOINTS                                   MESSAGE
mytest2   8f31272061a4   1         1            65s ago                                                OK
mytest1   8f31272061a4   1         1            118s ago   tcp://<Pending Load Balancer> => myweb:80   OK
```

**Comment by cjellick** [comment]
Putting in @ibuildthecloud as part of the --publish refactor

**Comment by cjellick** [comment]
this didnt change in the refactor and im closing as "works as expected" in that you are expected to specify the protocol as http if you want it published for http
