### ISSUE TITLE
Build stuck when `node_modules` is present

### ISSUE THREAD

**Issue by WoLfulus** [acorn-io/runtime#1535]
Acorn seems to get stuck when building an image with `node_modules` present (no console output at all). Adding the folder to `.dockerignore` doesn't make a difference (thought it could be because it was trying to transfer a really large context). As soon as I delete `node_modules` folder, it will build again.

I'm not sure why this happens, ~~but maybe it has something to do with how `node_modules` is getting installed on my end (I'm using pnpm, which makes a ton of symlinks and has a local store on disk's root)~~. EDIT: using `npm` instead of `pnpm` doesn't make a difference.

I tried with both k3s and docker-desktop's k8s, it behaves the same on both. 

Running on Windows 11.

**Comment by cjellick** [comment]
Apologies for the delayed response. Our "docs" acorn has a node_modules dir involved and works as expected (running `make serve-docs`) launches it.

Any further details to repro you can share. ...also could be that we fixed this or made it better since you reported the bug

**Comment by WoLfulus** [comment]
Ill try again and let you know

**Comment by cjellick** [comment]
closing due to age
