### ISSUE TITLE
Anomalies when linking Acorn apps

### ISSUE THREAD

**Issue by g-linville** [acorn-io/runtime#1536]
I noticed some strange things while trying to link multiple apps together:

- ~~When you link like `--link <app-name>:<container-name>` where the targeted container has multiple ports defined, only the first one in the list will actually be linked.~~ (Update: this is fixed now.)
- When I run an app with a container named `nginx` and link it to another app with a container named `nginx`, the new app is created but no containers actually start. When I look in that app's namespace, no Deployment even exists.
- When trying to link to an app that has multiple containers, I cannot get the link to work at all.

I think we should fix any potential problems relating to these observations and make the docs clearer about how to use this feature. The current docs seem to suggest that the syntax is `--link <other acorn name>:<name of container in the other acorn>` but experimentally I think it is actually `--link <other acorn name>:<alias for the one container running in the other acorn, to be used by this new acorn>`.

Edit: after talking with Darren, I think a docs update is all we really need here.

**Comment by g-linville** [comment]
Turns out that linking is far broader than I first thought, and it doesn't make sense to catch anything in the apiserver validation logic. So I'm just going to update the docs with some of the things I learned about links and that will suffice for this issue.

**Comment by g-linville** [comment]
Moving to QA. All I did was update docs.

**Comment by sangee2004** [comment]
Validated the workflow outlined in the newly added contents  https://docs.acorn.io/next/running/linking-acorns.
