### ISSUE TITLE
Improve VCS info captured by acorn when building images

### ISSUE THREAD

**Issue by njhale** [acorn-io/runtime#1622]
When building images, acorn captures some very basic VCS info about the repository in the current working directory. Today, this denotes only:
1. The commit hash of `HEAD`
2. Whether the working directory has uncommitted changes

We want to enrich the set of info captured to include:
- A reference to the upstream [remote]
- Whether the workspace is "clean" -- meaning NO non-ignored local files -- or not

See also: [vcs.go](https://github.com/acorn-io/acorn/blob/1d155cbe8be6bc4888ce7d9e78c625052107e390/pkg/vcs/vcs.go#L8)

**Comment by sangee2004** [comment]
Tested with - acorn version v0.7.0-alpha1-118-g6adb3fe9+6adb3fe9

`AppImagePullSuccess` event now includes the following information in "vcs" section:

```
            "vcs": {
                "modified": true,
                "remotes": [
                    "git@github.com:sangee2004/hub.git",
                    "git@github.com:acorn-io/hub.git"
                ],
                "revision": "c6a2c32111362fad04967b7832cd0854662c83b4"
            }

There is 1 issue with "modified" always being reported as "true".

Scenarios:
1. Deploy app from git hub repo without making any local changes. 

previous:
```
            "vcs": {}
        },
```
target:
```
            "vcs": {
                "modified": true,
                "remotes": [
                    xx
                ],
                "revision": "c6a2c32111362fad04967b7832cd0854662c83b4"
            }
```
 
In this case we expect "modified": false for "target"

2. Make some local changes but do not commit the changes.

```
        "previous": {
            "digest": "sha256:19eef54625c3132a759374490db3af209e5e974acb794381dc9c5a9be9f006fe",
            "name": "19eef54625c3132a759374490db3af209e5e974acb794381dc9c5a9be9f006fe",
            "vcs": {
                "modified": true,
                "remotes": [xxx
                ],
                "revision": "32c5239dc55b4a8f5981b657c5822237a4589f7d"
            }
        },
        "resourceVersion": "1222348",
        "target": {
            "digest": "sha256:80c8da7939201347c9f2e7060dbdaee55fba8f38a13eee1aabe82e038a531b0b",
            "name": "80c8da7939201347c9f2e7060dbdaee55fba8f38a13eee1aabe82e038a531b0b",
            "vcs": {
                "modified": true,
                "remotes": [
                   xxx
                ],
                "revision": "32c5239dc55b4a8f5981b657c5822237a4589f7d"
            }
        }
```
In this case `"modified": true` in `target` is correct.

3. Make some local changes and commit the changes.
```
        "previous": {
            "digest": "sha256:80c8da7939201347c9f2e7060dbdaee55fba8f38a13eee1aabe82e038a531b0b",
            "name": "80c8da7939201347c9f2e7060dbdaee55fba8f38a13eee1aabe82e038a531b0b",
            "vcs": {
                "modified": true,
                "remotes": [xx
                ],
                "revision": "32c5239dc55b4a8f5981b657c5822237a4589f7d"
            }
        },
        "resourceVersion": "1222419",
        "target": {
            "digest": "sha256:e139ea12b833c10addc3c349d536080c3569dd75e0cd8a764bb83029aef9b7b9",
            "name": "e139ea12b833c10addc3c349d536080c3569dd75e0cd8a764bb83029aef9b7b9",
            "vcs": {
                "modified": true,
                "remotes": [xx
                ],
                "revision": "c6a2c32111362fad04967b7832cd0854662c83b4"
            }
        }
```

In this case we expect "modified": false for "target".

Note - Even when I push the changes and deploy Apps , I see the `"modified": true` for the `AppImagePullSuccess` events.

**Comment by cjellick** [comment]
This might tie into our improve github oidc integration story

**Comment by cjellick** [comment]
extracting modified bug into it's own issue: https://github.com/acorn-io/runtime/issues/2336
