### ISSUE TITLE
Events related followup questions

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1638]
acorn version v0.7.0-alpha1-73-g17e3dd1e+17e3dd1e

When testing for event features, following questions came up  that might need more discussions:

@njhale has provided his initial thoughts on them:

1. Patch detail when using `acorn run —replace` can be made little more clear ===> Follow up on this 

This is the info I get when I did `acorn run --replace  -l mytest3:value3 -n mytest1` 
```
details:
  oldSpec:
    image: a007b22ba9c9c30491f338f9b72419389e78ddbfc740a7099d0660dbb3cb1d1c
    labels:
    - key: value1
      resourceName: mytest1
    - key: value2
      resourceName: mytest2
  patch:
  - op: remove
    path: /labels/1
  - op: replace
    path: /labels/0/key
    value: value3
  - op: replace
    path: /labels/0/resourceName
    value: mytest3
  resourceVersion: "1096819"
kind: Event
```

**Follow up:**
 There was some contention about this and I think we're going to forgo the patch and just put the entirety of the new spec under a `details.new` field.

2. Autoupgrade scenario 

When autoupgrade succeeds , we see only ImagePull event reported not `AppSpecUpdate`. We should expect to see this as well?
Checks done (at upgrade interval) for new image does not generate events. 
When `acorn update --pull <app>` is done , we only see  ImagePull event reported not `AppSpecUpdate similar to autoupgrade scenario.

```
SOURCE            NAME                               TYPE                  ACTOR          OBSERVED    DESCRIPTION
app/mytestevent   fb7a1dd8596a11374386f57d20eeb46f   AppImagePullSuccess   acorn-system   49s ago     Pulled index.docker.io/sangeetha/myfirstacorn:v0.0.4
app/mytestevent   6d4bff410ad8af9464dcf583ae0144da   AppImagePullSuccess   acorn-system   5m48s ago   Pulled index.docker.io/sangeetha/myfirstacorn:v0.0.3
app/mytestevent   d894e578ba9ad0f9fe0edcef352e859f   AppCreate             system:admin   5m52s ago   App acorn/mytestevent created
```
**Follow up:**
 No, as written, we wouldn't expect to see an AppSpecUpdate event. They are distinct events, and the controller is not actually changing the external `App` API when it happens (it's touching `AppInstance` API). I'm not sure it would be particularly useful to see an extra event for this either, but that's just my cursory thought and maybe others would disagree. We might want to bring this up as a discussion point.

3. Stop and start of app  - Can “DESCRIPTION” reflect that it was a stop or start action instead of a generic spec update ? ==> Follow up
 
**Follow up:**
 I think it can, but I'm not sure how much "smarts" we want to put into such a generic event type. At that point why not just emit a completely different event type too (e.g. `AppStarted|Stopped`). This is also something that could use being brought up as a discussion IMO.

4. Failed attempt to update Apps are not reported. Wanted to confirm if this also intentional? I tried to update with Acornfile that has invalid image . 

**Follow up:**
This is intentional, IMO it's not good to generate events for invalid info. I'm imagining a bad actor or broken controller generating TONS of events by submitting the bad info many times. I think this becomes less of a problem if we have rate limiting and/or event deduplication, but I'm not sure about the overall value of keeping this info as an event.

5. When using `acorn events -A -t <n>` , we display <n> events from each project . Is that the intended behavior? Or we want to show the latest <n> events across all projects .

**Follow up:**
I think the later is the only way that makes sense, or else we need to start talking about list precedence -- i.e. what order do I select from existing projects -- in the docs to meet the -n criteria.
BUT, I do think this is a UX concern that should be surfaced as a discussion

**Comment by njhale** [comment]
Just want to close the loop here, so below are the results of the respective follow ups:

1. We left the patch as is
2. Autoupgrade is going to get it's own event type
3. I still think separate event types make sense for this use case. We're already doing this in manager to some extend when we stop and remove apps in sandbox
4. Still intentional, see reasoning in OP
5. `-A` is no longer a supported option
