### ISSUE TITLE
Limit the number of events that can exist

### ISSUE THREAD

**Issue by njhale** [acorn-io/runtime#1709]
## Description

Introduce a mechanism for configuring and enforcing an upper bound on the number of events that can exist at a given time.

## Requirements

A solution will:
- maintain a "soft" upper bound on the number of events; i.e. the system can temporarily exceed the limit for short periods.
- ~~surface a configuration point on Acorn~~

## Motivation

Today, clients can record an unlimited number of events, which can consume an unlimited amount of resources. Capping events lets us draw a box around their potential impact on resource utilization.

## Notes

- ~~We could extend Quota to bound Events~~
- The simplest approach involves a controller that repeatedly deletes the oldest known event until the number of events is less than or equal to the upper bound.
- ~~Another approach is to think of the bounded event set as a fixed-length circular queue; we write events in the order they were received until we fill up the queue, then circle back to the beginning and overwrite the older entries to record new events~~
- ~~Another approach is to reject write requests once the upper bound is hit and leave it to [some other process](https://github.com/acorn-io/acorn/issues/1708) to free up space~~
- ~~Consider capping events on a per-Project or per-Account basis so that clusters can scale with usage. A constant number of events per-cluster probably won't scale well since one bad tenant can hog all the space by triggering more events than others.~~

**Comment by njhale** [comment]
In a discussion today with @ibuildthecloud we came to the conclusion that rate-limiting event creation would be a better solution than imposing a hard cap on the number of events.

**Comment by sangee2004** [comment]
Tested with acorn version`v0.8.0-rc4+b6a95e8a` on local clusters.

Created 1500 events ( this was done directly using `kubectl`)
After 5 minutes , acorn events from all projects reported only 1000 latest events.
Deployed few apps.
This result in more events getting created and count getting to > 1000 .
In the next 5 minutes, event count gets back to 1000 . Older events get deleted to keep the count to 1000. Events relating to deployed app continue to be present.
