### ISSUE TITLE
ImageAllowRules - Not allowed to update images (not prompted for allowing images)

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1712]
acorn version v0.7.0-alpha1-148-g7909ed41+7909ed41

Steps to reproduce the problem:
Install acorn with `--features image-allow-rules=true`

Scenario1:
Deploy app from Acornfile.
When prompted for allowing images , select "yes" and allow for app to get deployed successfully.( Do you want to allow this app to use this (POTENTIALLY DANGEROUS) image? yes (this ID or SHA only))
Make changes to Acornfile and update app.  There is no prompt for allowing the new image sha and update fails
```
 acorn run --update -n mytest1 . 
....
 => => pushing manifest for 127.0.0.1:5000/acorn/new2:latest@sha256:d9350c3bbf3b1be57140aa42166ce0da845f6775305ec22094a1f1128cd65ea0                                                                                        0.0s
  ✗  ERROR:  image <> is not allowed by any ImageAllowRule in this project

```
Scenario2:
Deploy app from image  and choose to allow only this image.
Update app with a new image version. There is no prompt for allowing the new image  and update fails
```
acorn run --update -n mytestimage sangeetha/myfirstacorn:v0.0.2
  ✗  ERROR:  image <> is not allowed by any ImageAllowRule in this project
```

Expected Behavior:
There should be a prompt to allow for images on app updates.

**Comment by cjellick** [comment]
I don't want the imageAllowRules feature to be blockers. Moving out of of v0.7

**Comment by iwilltry42** [comment]
Waiting for #1742 to be merged before.
Afterwards it's just a copy-paste to add the same code to `AppUpdate` that we have in `AppRun` already.

**Comment by sangee2004** [comment]
Blocked on testing this workflow because of regression introduced in - https://github.com/acorn-io/runtime/issues/1698#issuecomment-1639005670
