### ISSUE TITLE
acorn copy command

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#1809]
We want the equivalent of `crane copy`, but for acorn images, built right into the acorn cli

**Comment by sangee2004** [comment]
Tested with acorn version - ` v0.8.0-alpha7-114-gbf4c72ea+bf4c72ea`
Able to use `acorn copy` command for the following scenarios:
1. copy an image from the internal registry to a remote registry 
2. copy images between remote registries
3. copy entire repositories between remote registries (with the -a option)

@g-linville We are not allowed to copy all tags of an image from  internal registry to a remote registry using "-a" option. 
Do we expect for this to succeed ? If not , can the error message for this be improved ?

```
acorn images mytestssh
REPOSITORY   TAG       IMAGE-ID
mytestssh    v0.0.1    dd805b801e98
mytestssh    v0.0.3    c5d1f2026afc
mytestssh    v0.0.2    48b4edb63751

 % acorn copy -a mytestssh ghcr.io/<accountname>/sshtestp
  ✗  ERROR:  websocket: close 1011 (internal server error): [ags/list?n=1000: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/mytestssh Type:repository]]]
```

**Comment by g-linville** [comment]
@sangee2004 yeah, `--all-tags` is only valid with remote registries and not the local one. I'm hesitant to look for this and catch the error in case the user has a local image that matches the name of a remote registry and it might cause them issues.

For example, say I have a remote Acorn image at `docker.io/grantlinville/myacorn:v1`. I build and push `docker.io/grantlinville/myacorn:latest`. Now I have a local image called `docker.io/grantlinville/myacorn:latest`. If I were to then attempt to copy both tags from my Docker Hub to my GHCR by running `acorn copy --all-tags docker.io/grantlinville/myacorn ghcr.io/g-linville/myacorn`, the apiserver would get confused and think that I am wrongly referring to a local image, when I am actually trying to refer to a valid remote repository. So I would prefer to leave this as is.

`acorn copy --help` indicates that `--all-tags` does not work with local images.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.8.0-rc4-58-gbe49d0bd+be49d0bd`

1. Acorn copy works only with local credentials now.Need to make error messages relating to this more obvious to users tracked in https://github.com/acorn-io/runtime/issues/2119

2. acorn copy with source being a tag does not work. I am not sure how this is suppose to work.

```
acorn image copy ghcr.io/sangee2004/myfirstacorn:v0.0.1 myfirstacorncopy
Copying ghcr.io/sangee2004/myfirstacorn:v0.0.1 to myfirstacorncopy [57002292/57002292]  100% | 0s
```
This should have copied the images to  `ghcr.io/sangee2004/myfirstacorncopy` ?
I dont see this repo created and dont see any local images as well.

When i use it with "-a" it gives a "manifest unknown" error even when source repo is present.
```
acorn image copy -a ghcr.io/sangee2004/testsignature  hello
  ✗  ERROR:  GET https://ghcr.io/v2/sangee2004/testsignature/manifests/latest: MANIFEST_UNKNOWN: manifest unknown
```
