### ISSUE TITLE
Not able to set memory for service apps.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#1832]
**Acorn version** - v0.7.1-46-ge262f63c+e262f63c

**Steps to reproduce the problem:**

1. Have default compute class set as follows
```
 acorn offerings computeclass
NAME      DEFAULT   MEMORY RANGE   MEMORY DEFAULT   REGIONS   DESCRIPTION
cc2       *         10M,20M,30M    20M              local     Large compute for linux on arm64
```

2. Build a service image 

`acorn build -t mytestservice:v0.0.1`

Acornfile
```
services: "secret-getter": {
  generated: job: "create-secret"
}

jobs: "create-secret": {
  image: "ubuntu"
  files: "create.sh": """
  #!/bin/sh
  sleep 180
  cat > /run/secrets/output<<EOF
  services: "secret-getter": {
      secrets: ["output"]
   }
   secrets: "output": {
     type: "opaque"
     data: 
        key: "value"
   }
  """
  entrypoint: ["./create.sh"]
}

secrets: output: {
        type: "generated"
        params: job: "create-secret"
}
```

3. Deploy app that uses this service image by setting memory to "30M"

`acorn run -m 30M -n mytestservice `

Acornfile
```
containers: {
  nginx: {
    image: "nginx"
    env: {
     "SECRET": "@{secrets.mysec.output.key}"
}
}
}
services: {
     mysec: {
	image: "mytestservice:v0.0.1"
        }
}
```

Once the apps get deployed , notice that the pods of the service app gets deployed with default memory - 20M .
```
  "resources": {
      "limits": {
          "memory": "20M"
      },
      "requests": {
          "cpu": "14m",
          "memory": "20M"
      }
  },
```

**Expected Behavior:**
 Pods of the service app should gets deployed with memory set in the CLI using `-m` option which is `30M` .

4. Deploy app that uses this service image by setting memory to "30M" in Acornfile

`acorn run -n mytestservice `

Acornfile
```
containers: {
  nginx: {
    image: "nginx"
    env: {
     "SECRET": "@{secrets.mysec.output.key}"
}
}
}
services: {
     mysec: {
	image: "mytestservice:v0.0.1"
        memory: 30M
        }
}
```
Once the apps get deployed , notice that the pods of the service app gets deployed with default memory - 20M .
```
  "resources": {
      "limits": {
          "memory": "20M"
      },
      "requests": {
          "cpu": "14m",
          "memory": "20M"
      }
  },
```

**Expected Behavior:**
 Pods of the service app should gets deployed with memory set in the Acornfile which is `30M` .

**Comment by cjellick** [comment]
relevant internal convo around this: https://acorn-io.slack.com/archives/C03FU91U4SX/p1687537435132739. note - that link wont work for most.

At the time of this comment, no clear conclusions for that thread, else i would have copied here

**Comment by sangee2004** [comment]
Tested with acorn `v0.9.2-51-gcf5ba1d5`
Able to set memory successfully on service apps using `memory` tag in both command line and in Acornfiles.
