### ISSUE TITLE
Support `acorn edit`

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#1849]
Like `kubectl edit`, but nuttier.

**Comment by cjellick** [comment]
Exists?

**Comment by cjellick** [comment]
I think @ibuildthecloud said he did this

**Comment by sangee2004** [comment]
Tested with `acorn version v0.9.2-28-ga822ff9d+a822ff9d`

`acorn edit` is now available for apps and secrets.

We are able to edit apps and secrets using `acorn edit` successfully.

Logged the following 2 related issues - https://github.com/acorn-io/runtime/issues/2357  and https://github.com/acorn-io/runtime/issues/2356.
