### ISSUE TITLE
`acorn logs` don't work while things are deleting

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#1887]
`acorn logs` don't work while things are deleting.  That makes it hard to troubleshoot stuck deleting stuff.

> I'm pretty sure this is because I look at !DeletionTimestemp.IsZero() as when to decide to terminate

[Slack Message](https://acorn-io.slack.com/archives/C03FU91U4SX/p1688623023927599?thread_ts=1688623023.927599&cid=C03FU91U4SX)

**Comment by keyallis** [comment]
I've added an integration test to cover this functionality, that test pulls in a new acornfile that will hang when a deletion is triggered and then checks to make sure it gets a new log message following that event
