### ISSUE TITLE
Change Acorn volumes back to using a public name strategy

### ISSUE THREAD

**Issue by g-linville** [acorn-io/runtime#1892]
We used to use a public name strategy for Acorn volumes in the apiserver, but we switched away from it due to bugs surrounding rebinding existing volumes.

After talking through it again, we want to switch back to using public name, with the following constraints:

1. Once a public name is set on a volume, it must never change, even when rebinding.
   - e.g. if I create an app called `app1` that has a volume called `app1.myvol`, and I delete `app1` and rebind `app1.myvol` to a new app called `app2`, the volume's name is still `app1.myvol`; it does not change.
2. When creating a new volume, the controller needs to check to make sure that the public name of the new volume will not match the public name of an existing volume in order to avoid duplicate names.
   - Continuing the previous example, if I were to try to deploy `app1` again, it will try to create another volume called `app1.myvol`, but the controller should block this, since a volume with public name `app1.myvol` already exists.

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.8.0-alpha7-133-ge68fb042+e68fb042`

1. Deploy app - `mytest1` that uses volume using following Acornfile 
```
args: {
fileName: "hello.html"
fileContent: "content"
}
containers: {
    frontend: {
        build: "."
        cmd: ["/root/start.sh", args.fileContent,args.fileName]
        dirs: {
            "/scratch": "volume://scratch-data"
        }
        sidecars: {
            sidecar: {
            ports: publish: "80/http"
            image: "nginx"
            dirs: {
                "/usr/share/nginx/html/test1": "volume://scratch-data"
            }
          }
        }
}
}
volumes:
{
"scratch-data": {}
}
```

2. once app is deployed , volume gets created with public name
```
acorn volumes
NAME                   BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS    ACCESS-MODES   CREATED
mytest1.scratch-data   scratch-data   10G        local-path     bound     RWO            11s ago
```

3. Delete app - `test1` (without deleting volumes) - `acorn rm test1`

4. Deploy another app that binds to existing volume- -`acorn run -n mytestbindvol -v mytest1.scratch-data:my-data` using following Acornfile
```
containers: {
mynginx: {
ports: publish: "80/http"
image: "nginx"
dirs: {
"/usr/share/nginx/html/test1": "volume://my-data"
}
}
}
```

4. Once app gets deployed successfully, the name of the existing volume continues to remain the same as expected:

```
acorn volumes
NAME                   BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS    ACCESS-MODES   CREATED
mytest1.scratch-data   my-data-bind   10G        local-path     bound     RWO            2m6s ago
```

5.  Try to deploy app - `mytest1` again from Step1.

6. App deployment does not succeed with following error which is as expected:
```
acorn apps
NAME            IMAGE          DIGEST         HEALTHY   UP-TO-DATE   CREATED    ENDPOINTS                                                                MESSAGE
mytest1         0c464d0e3ee6   0c464d0e3ee6   0         0            65s ago                                                                             [defined: cannot use existing volume pvc-13623c59-518a-414f-844f-f15534fa4d52 - it is in phase Bound] [containers: frontend: [pending create]] [volumes: scratch-data: [pending create]] [controller: [routes.go:78] cannot use existing volume pvc-13623c59-518a-414f-844f-f15534fa4d52 - it is in phase Bound]
```

7.  Delete app  that was created in step4 - `acorn rm mytestbindvol`

8. Try to deploy app - `mytest1` again from Step1.

App deployment  succeeds now and uses the existing volume .
```
acorn volumes
NAME                   BOUND-VOLUME   CAPACITY   VOLUME-CLASS   STATUS    ACCESS-MODES   CREATED
mytest1.scratch-data   scratch-data   10G        local-path     bound     RWO            18m ago
```
