### ISSUE TITLE
Always return event details

### ISSUE THREAD

**Issue by njhale** [acorn-io/runtime#1906]
## Description

Requests to list and watch events should never strip event details.

## Background

The details field of a runtime event allows for context specific information to be added. For example, VCS info is included for AppImagePull events.

By default, the runtime API elides the field on list and watch unless otherwise opted-in by the request. The idea was to reduce the overhead when working with lots events containing potentially large `details`.

## Motivation

This was likely a premature optimization since, in practice, the details field has been used to store small payloads, similar in size to their respective objects.

**Comment by njhale** [comment]
Opened #1913 to address something I missed in #1908

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.8.0-alpha7-98-gbb130866+bb130866 `
1. `acorn events -o json` always returns `details` info.
2. There is no support for "--details" flag anymore.
