### ISSUE TITLE
Improve auto-upgrade enablement UX

### ISSUE THREAD

**Issue by tylerslaton** [acorn-io/runtime#2000]
There are some current UX gaps when it comes to setting auto-upgrade. We should improve them such that each of the below items are addressed:

* Keep the structure API as-is
* the server side/backend/daemon should only look at isPattern() or autoUpgrade == true. those are the only scenarios that puts an app into auto-upgrade mode. Implications of this:
  * If an app just has notifyUpgrade set, it is NOT autoUpgrade
  * If an app just has interval set, it is NOT autoUpgrade
  * If an app just has a pattern for its tag, it IS autoUpgrade
  * If app just as autoUpgrade set, it IS autoUpgrade
* CLI should compensate to turn on autoUpgrade if related fields are set. it should set autoUpgrade to true if:
  * the interval is set
  * if notifyUpgrade is set
  * the image is a pattern (maybe this one is not necessary and it could actually possibly complicate things)
* we'll have to consider update scenarios that turn off auto-upgrade. Seems like one cannot currently unset interval from the cli. if thats true, we should fix that. This is tracked in https://github.com/acorn-io/runtime/issues/2008

**Comment by tylerslaton** [comment]
Related https://github.com/acorn-io/manager/issues/801

**Comment by tylerslaton** [comment]
> we'll have to consider update scenarios that turn off auto-upgrade. Seems like one cannot currently unset interval from the cli. if thats true, we should fix that.
Everything except this is adjusted now. Going to be looking at that and the other linked issue.

**Comment by tylerslaton** [comment]
Also realted https://github.com/acorn-io/runtime/issues/1996

**Comment by sangee2004** [comment]
Tested with acorn version v0.8.0-alpha7-210-g2e8339a2+2e8339a2

Following tests are done from CLI:
1. Deploy apps with images in autoupgrade format (no --auto-upgrade  or --interval set or --notify-upgrade)
2. Deploy apps with only  `--notify-upgrade` set
3. Deploy apps with only `--interval` set
4. Deploy apps with only `--auto-upgrade` set

Autoupgrade gets triggered as expected in all the above cases.

**Comment by sangee2004** [comment]
Following tests were done for nested Acorns:

Deploy nested apps using the following Acornfile:

```
acorns: {
    "my-acorn1": {
        image: "docker.io/sangeetha/myfirstacorn:v#.#.#"
    }
   "my-acorn2": {
       image: "docker.io/sangeetha/myfirstacorn:latest"
        notifyUpgrade: true
   }
    "my-acorn3": {
        image: "docker.io/sangeetha/myfirstacorn:latest"
        autoUpgradeInterval: "15s"
    }
   "my-acorn4": {
       image: "docker.io/sangeetha/myfirstacorn:latest"
       autoUpgrade: true
        notifyUpgrade: true
   }

}
```

Only `my-acorn1` and `my-acorn4` will get deployed in auto upgrade mode as expected.


```
acorn apps -j acorn
NAME                     IMAGE                                             COMMIT    HEALTHY   UP-TO-DATE   CREATED    ENDPOINTS                                                                              MESSAGE
mytestnested             e4294669211c                                                0         0            110m ago                                                                                          OK
mytestnested.my-acorn1   index.docker.io/sangeetha/myfirstacorn:v46.0.0*             1         1            110m ago   http://myweb-mytestnested-my-acorn1-b3a46aa5-8985526f.local.oss-acorn.io => myweb:80   OK
mytestnested.my-acorn2   docker.io/sangeetha/myfirstacorn:latest                     1         1            110m ago                                                                                          OK
mytestnested.my-acorn3   docker.io/sangeetha/myfirstacorn:latest                     1         1            110m ago                                                                                          OK
mytestnested.my-acorn4   docker.io/sangeetha/myfirstacorn:latest*                    1         1            110m ago   http://myweb-mytestnested-my-acorn4-7dbfce55-5ccfcc15.local.oss-acorn.io => myweb:80   OK
```
