### ISSUE TITLE
Feature: Signing and Verifying images from the CLI

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/runtime#2043]
Add the ability to sign images with a local private key from the CLI.
Additionally add an option to verify images using either a local public key or a remote reference to GitHub or Acorn Manager Accounts.

**Comment by sangee2004** [comment]
Tested using -`v0.8.0-rc4+b6a95e8a`

Able to sign and verify images. Issues found when testing this feature are tracked in separate issues:
 
https://github.com/acorn-io/runtime/issues/2063
https://github.com/acorn-io/runtime/issues/2064
https://github.com/acorn-io/runtime/issues/2067
https://github.com/acorn-io/runtime/issues/2069
