### ISSUE TITLE
IARs should require an images scope to apply to anything

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/runtime#2061]
Currently, it's possible to define an IAR with only a signatures requirement, thus the IAR doesn't actually apply to any image, sicne no scope is set and we don't have a default.

We decided to require an images scope when creating an IAR.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.8.0-rc4-13-g2e9f5e8a+2e9f5e8a`

IAR fails to get created with no `images` field and following error message is presented to the user:

```The ImageAllowRule "testrules-project" is invalid: images: Required value: the images scope must be set to define which images this rule applies to````
