### ISSUE TITLE
Inform users when local credentials are used for builds

### ISSUE THREAD

**Issue by njhale** [acorn-io/runtime#2068]
## Description

Print a message to stdout when local acorn (or docker) credentials are used during `acorn build`.

## Motivation

Acorn builds prefer local credentials -- set with `acorn login -l` or `docker login <registry>` -- over credentials set with `acorn login`, but don't indicate if local credentials are in use at build time. So when the cause of a build error is bad local creds, it can be hard to spot.

## Implementation Details

Discussed in the acorn company slack: User facing messages, like the one described in this issue, should basically hit `fmt.Println`, rather than `logrus` or `pterm`; the later being reserved for printing the final error message.

**Comment by sangee2004** [comment]
Tested with acorn version `v0.8.0-rc4-13-g2e9f5e8a+2e9f5e8a`

1. Use `acorn login -l docker.io` ( or login to docker using `docker login`)
2.Deploy app from Acornfile: 
```
args: {
	newApp:  true
	oldtext: "old"
	newtext: "v17"
}
containers: {
	myweb: {
	image: "nginx"
	ports: publish: "80/http"
	files: {
		"/usr/share/nginx/html/index.html": std.ifelse(args.newApp, args.newtext, args.oldtext)
		"/usr/share/nginx/html/test.html":  "test1"
		"/usr/share/nginx/html/test2.html": "test2"
	}
}
}
```

Following line is printed in the output of CLI when deploying apps from Acornfile:

"Used local credentials for: index.docker.io"
