### ISSUE TITLE
Builders should act like they are panicking when shutting down

### ISSUE THREAD

**Issue by thedadams** [acorn-io/runtime#2081]
The builders use `logrus.Fatal` every time they shutdown. This produces a false-positive for issues.

It would be better if a stack-trace wasn't produced on a graceful shutdown to avoid this confusion.

**Comment by thedadams** [comment]
The easiest way I found to test this is the following:
1. Run `runtime` locally with `acorn install`.
2. Run a build so that the `buildkitd` deployment is created.
3. In two separate terminals watch the logs of both containers in the pod: `kubectl -n acorn-image-system logs buildkitd-7cd9fd44c6-wwgxc -f` and `kubectl -n acorn-image-system logs buildkitd-7cd9fd44c6-wwgxc -c service -f`
4. In another terminal, restart the deployment: `kubectl -n acorn-image-system rollout restart deployment buildkitd`

Once the fix is in, there should be no stack traces printed when the containers exit.

**Comment by sangee2004** [comment]
Able to reproduce the issue on seeing stack traces printed in the logs when testing with `acorn version v0.8.0-rc4-27-g20d5e79e+20d5e79e` by following the steps mentioned in the issues.


Tested with `acorn version v0.8.0-rc4-29-g6a019fe7+6a019fe7`
When following the same steps mentioned in the issue , there is no stack traces printed in the logs.

Following are the logs that were printed when attempting `kubectl -n acorn-image-system rollout restart deployment buildkitd`
 
`kubectl -n acorn-image-system logs buildkitd-686c95c556-p27f6 -f `
```
time="2023-08-17T17:50:34Z" level=info msg="stopping server"
buildkitd: context canceled
rpc error: code = NotFound desc = an error occurred when try to find container "402a5b067b4b4bbce4f76e0aeb7103136b9a1e7170955d8a80d0d547f39a618a": not found%                 
```

kubectl -n acorn-image-system logs buildkitd-686c95c556-p27f6 -c service -f 
```
time="2023-08-17T17:50:34Z" level=fatal msg="accept tcp [::]:5000: use of closed network connection"
rpc error: code = NotFound desc = an error occurred when try to find container "4da741bf1818c18ca92d779583dd39b76f07bd12c5ec4f11de85f6766702a5a7": not found%                 
```
