### ISSUE TITLE
Deploying app from repository that was deleted and recreated results in MANIFEST_UNKNOWN error.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2082]
**acorn version** - `v0.8.0-rc4-13-g2e9f5e8a+2e9f5e8a`

**Steps to reproduce the problem:**
1.  From project p1 , deploy app using images from external repo - `docker.io/sangeetha/mytestacorn:v0.0.1`
2. Once app is deployed successfully , delete the repository - `docker.io/sangeetha/mytestacorn` from dockerhub UI.
3. From another project say p2  , build and push a new version of `docker.io/sangeetha/mytestacorn:v0.0.1`
4. From project p1 , deploy another app using `index.docker.io/sangeetha/mytestacorn:v0.0.1`
```
acorn run -n mytest2 index.docker.io/sangeetha/mytestacorn:v0.0.1
  ✗  ERROR:  GET https://index.docker.io/v2/sangeetha/mytestacorn/manifests/sha256:a04b44fc0a536475af0a2a949554708a51a1cc9be1784d33359ff9312da074b6: MANIFEST_UNKNOWN: manifest unknown; unknown manifest name=sangeetha/mytestacorn revision=sha256:a04b44fc0a536475af0a2a949554708a51a1cc9be1784d33359ff9312da074b6
```
We have the following remote image entry that was created when app was deployed in step1.
```
acorn images                                              
REPOSITORY                              TAG       IMAGE-ID
index.docker.io/sangeetha/mytestacorn   v0.0.1    a04b44fc0a53
```

**Note** - If I delete this image entry , i am able to deploy app successfully using this image again.

Also If i use image name as just `sangeetha/mytestacorn:v0.0.1` in step4 , then I do not see this problem. 
App deployment using this command would succeed (when used in step4)
```
 acorn run -n mytest2 sangeetha/mytestacorn:v0.0.1 
```

**Comment by cjellick** [comment]
Can you retest to see if Darren's removal of remote images fixed this?

**Comment by sangee2004** [comment]
Tested with - acorn version `v0.8.0-rc4-58-gbe49d0bd+be49d0bd`

This issue is not seen anymore. Able to deploy app from repository that was deleted and recreated successfully following steps mentioned in the issue.
