### ISSUE TITLE
Change `acorn copy` so that it only copies from remote to remote

### ISSUE THREAD

**Issue by g-linville** [acorn-io/runtime#2096]
We don't want to involve local images in this command anymore. So we can remove all the server-side stuff and make this run entirely in the CLI.

We also want to support a new syntax like this:

`acorn copy registry.example.com/repo/image:tag newtag`

**Comment by sangee2004** [comment]
Tested with acorn version v0.8.0-rc4-58-gbe49d0bd+be49d0bd

Acorn copy works only with local credentials now.
Able to copy images between remote registries.
We are not allowed to operate on local images in source or remote repositories.
Able to tag images successfully using acorn image copy -a <image in remote repo>  <imagetag>
Related issues seen when testing this feature:

https://github.com/acorn-io/runtime/issues/2119
https://github.com/acorn-io/runtime/issues/2121
https://github.com/acorn-io/runtime/issues/2122
