### ISSUE TITLE
Improve error message when `acorn run`ing private image unauthenticated

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/runtime#2101]
For pull/push/details, we send along the local credentials (docker creds). But we don't do that for `run`, since they would have to be stored in the cluster after the request and this should be a conscious decision.
So rather then returning the registry's "UNAUTHORIZED" message, we should catch that and give the user a hint about using `acorn login` first.

Error messages coming back to the client - tested for 3 big registries:

- GHCR: `"GET https://ghcr.io/token?scope=repository%3A<REPO>%2Forder-sync%3Apull&service=ghcr.io: UNAUTHORIZED: authentication required"`
- docker.io: `"GET https://index.docker.io/v2/<REPO>/manifests/<IMAGE>: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:<REPO> Type:repository]]"`
- Harbor: `"GET https://harbor.foo.io/v2/<REPO>/manifests/<TAG>: UNAUTHORIZED: unauthorized to access repository: <REPO> action: pull: unauthorized to access repository: <REPO>, action: pull"`

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.8.0-rc4-58-gbe49d0bd+be49d0bd`

Following error message is presented when attempting `acorn run` on private  images when we are not logged into the registry:

```
% acorn run -n test1 ghcr.io/sangee2004/mytestacorn         
  ✗  ERROR:  not authorized to pull ghcr.io/sangee2004/mytestacorn - Use `acorn login <REGISTRY>` to login to the registry
 % acorn run -n test1 docker.io/sangeetha/mytestnewacorn:v0.0.1
  ✗  ERROR:  not authorized to pull docker.io/sangeetha/mytestnewacorn:v0.0.1 - Use `acorn login <REGISTRY>` to login to the registry
```
