### ISSUE TITLE
Not able to copy images from remote repositories

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2111]
**acorn version**  - v0.8.0-rc4-47-g80dd7169+80dd7169

**Steps to reproduce the problem:**
1. Have login credentials created for `docker.io` and `ghcr.io` using `acorn login`
2. Copy image between remote repositories using `acorn image cp  docker.io/sangeetha/myfirstservice:v0.0.1   ghcr.io/sangee2004/myfirstservice:v0.0.1`
This fails:
```
  ✗  ERROR:  websocket: close 1006 (abnormal closure): unexpected EOF
```
Note - `acorn image copy` works when we have the source image present locally.

1. `acorn build -t docker.io/sangeetha/myfirstservice:v0.0.1 .`
2. `acorn image cp  docker.io/sangeetha/myfirstservice:v0.0.1   ghcr.io/sangee2004/myfirstservice:v0.0.1` --> works.

**Comment by g-linville** [comment]
This should be fixed at the same time as #2096.

**Comment by g-linville** [comment]
`acorn copy` now totally ignores local images and can only be used with remote registries.

**Comment by sangee2004** [comment]
Tested with acorn version -`v0.8.0-rc4-58-gbe49d0bd+be49d0bd`

Able to copy images between remote registries when local credentials are available for both source and destination repos .  Related issue tracked in - https://github.com/acorn-io/manager/issues/879
