### ISSUE TITLE
fix: `image verify` should not print key on failure

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/runtime#2115]
As reported by @g-linville via Slack

This happened when referencing a private key file during verification.
First of all, given a path to a file, we shouldn't log the contents.
Second, we should reject private keys to avoid sending them to the server.

Solutions:
a) extract the public key from the private key and use that one
b) just reject as soon as we notice it's a private key

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.8.0-13-gab9787b8+ab9787b8`

Following error message is presented to user when `acorn image verify` is done using a privatekey.
```
  ✗  ERROR:  failed to load public key from invalid multi-line key reference
```
