### ISSUE TITLE
Improve error message to indicate that local credentials needed for `acorn image copy` 

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2119]
acorn version  - v0.8.0-rc4-58-gbe49d0bd+be49d0bd

**Steps to reproduce the problem:**
1. Attempt `acorn image copy` between 2 remote registries 

2. Have login credentials created for `docker.io` and` ghcr.io` using `acorn login`
3. Copy image between remote repositories using `acorn image cp  docker.io/sangeetha/myfirstserviceagain:v0.0.1   ghcr.io/sangee2004/myfirstservice:v0.0.1`
This fails with following error message:
```
  ✗  ERROR:  GET https://ghcr.io/token?scope=repository%3Asangee2004%2Fmyfirstserviceagain%3Apull&service=ghcr.io: DENIED: requested access to the resource is denied
```
**Expected Behavior:**
`acorn image copy` succeeds only when we have local credentials made available using `acorn login -l` command.

Error message presented to the user should provide this information.

**Comment by g-linville** [comment]
I improved the help and error messages for `acorn copy`.

**Comment by sangee2004** [comment]
acorn version - `v0.8.0-rc5+15fc5478`

Following error message presented when `acorn image copy` is attempted when no local creds are present:
```
Registry authorization failed. Ensure that you have the correct permissions to push to this registry. Run 'acorn login -l <registry>' if you have not logged in yet.
```


Following text seen in `acorn image copy --help`
````

  This command copies Acorn images between remote image registries.
  It does not interact with images stored in the Acorn internal registry, or with the Acorn API in any way.
  To set up credentials for a registry, use 'acorn login -l <registry>'. It only works with locally stored credentials.

```
