### ISSUE TITLE
acorn -v  is failing with unknown flag

### ISSUE THREAD

**Issue by sadhugit** [acorn-io/runtime#2139]
1. brew install acorn-io/cli/acorn
2. perform acorn -v

actual results:

Documentation says:
Linux or macOS
brew install acorn-io/cli/acorn

 verify binary (assume local directory)
acorn -v

But when I pull the acorn and run the acorn -v command it fails with the below error

Use "acorn [command] --help" for more information about a command.

  **✗  ERROR:  unknown shorthand flag: 'v' in -v**

**Comment by cjellick** [comment]
Apologies, we've replaced this with `acorn version`

**Comment by cjellick** [comment]
I'm going to close this. Feel free to re-open if you feel it needs more follow up
