### ISSUE TITLE
fix: enable cert-manager for custom cluster-domains

### ISSUE THREAD

**Issue by iwilltry42** [acorn-io/runtime#2153]
As reported by Beta User.

To replicate:
1. Install cluster with AcornDNS disabled (optional) and custom cluster-domain and a cert-manager issue defined: `acorn install --acorn-dns=disabled --cluster-domain my.domain.com --cert-manager-issuer=letsencrypt-prod`
2. Run an app and set a custom endpoint:: `acorn run -p foo.my.domain.com:webapp ghcr.io/acorn-io/hello-world:v1`
3. Observe, how `foo.my.domain.com` gets an https endpoint and the generated endpoint does not

Investigation:
- Inspecting the Ingress objects shows  that the cert-manager annotation is not set on the generated endpoint
- https://github.com/acorn-io/runtime/blob/87e1aef3da18c125d34faa6631f8147d61645203/pkg/publish/cert.go#L151 only sets the annotation if it's a custom domain

**Comment by sangee2004** [comment]
Able to reproduce the issue with acorn version -`v0.8.0+89036514`

1. Install cluster with AcornDNS disabled (optional) and custom cluster-domain and a cert-manager issue defined: acorn install --acorn-dns=disabled --cluster-domain my.domain.com --cert-manager-issuer=letsencrypt-prod
2. Run an app and set a custom endpoint  -  `acorn run -p foo.my.domain.com:webapp ghcr.io/acorn-io/hello-world:v1`

```
acorn apps
NAME             IMAGE                             COMMIT         CREATED     ENDPOINTS                                                                        MESSAGE
dark-waterfall   ghcr.io/acorn-io/hello-world:v1   eab5f8c77bd6   4m51s ago   https://foo.my.domain.com, http://webapp-dark-waterfall-11d87400.my.domain.com   OK
```

Tested with `acorn version v0.8.0-26-g6dfde7eb+6dfde7eb`

Following the same set of steps , we get `https` for generated endpoint as well.

```
acorn apps
NAME           IMAGE                             COMMIT         CREATED   ENDPOINTS                                                                       MESSAGE
polished-dew   ghcr.io/acorn-io/hello-world:v1   eab5f8c77bd6   7s ago    https://foo.my.domain.com, https://webapp-polished-dew-4fbaa3dc.my.domain.com   OK
```

**Comment by iwilltry42** [comment]
So this is OK to close @sangee2004 ? :+1:
