### ISSUE TITLE
Running upgrade on an Acorn with auto-upgrade set may disable auto-upgrade

### ISSUE THREAD

**Issue by thedadams** [acorn-io/runtime#2161]
1. Run an Acorn with a non-auto-upgrade tag (like `main`) with `--auto-upgrade`
2. After the Acorn becomes ready, run `acorn update` on the Acorn.
3. Auto-upgrade will be disabled.

The expected behavior is that auto-upgrade was enabled for an app, then it must be explicitly disabled on future calls to update.

**Comment by sangee2004** [comment]
Reproduced this issue on older version of runtime wth following steps:

1. Deploy app with `--auto-upgrade` option
`acorn run -n mytestautonew --auto-upgrade sangeetha/myfirstacorn:v0.0.1`
``` 
acorn apps
NAME            IMAGE                            COMMIT    CREATED     ENDPOINTS                                                 MESSAGE
mytestautonew   sangeetha/myfirstacorn:v0.0.1*             5s ago      http://myweb1-mytestautonew-5801bbaa.local.oss-acorn.io   OK
```
2. Update app
`acorn update -e test1=value1 mytestautonew `

3. After the update , app does not have auto-upgrade flag set anymore.

When listing the app, image does not have "*" anymore which is to indicate autoupgrade.
``` 
acorn apps
NAME            IMAGE                            COMMIT    CREATED     ENDPOINTS                                                 MESSAGE
mytestautonew   sangeetha/myfirstacorn:v0.0.1*             5s ago      http://myweb1-mytestautonew-5801bbaa.local.oss-acorn.io   OK
```
Also spec field has "autoUpgrade" set to false
```
acorn apps mytestautonew -o json | grep autoUpgrade                    
                "autoUpgrade": false
````


Tested the same set of steps with `acorn version v0.8.0-26-g6dfde7eb+6dfde7eb`

After step 3,  app does contunues to have `auto-upgrade` flag set.

```
 acorn apps
NAME            IMAGE                                      COMMIT    CREATED     ENDPOINTS                                                   MESSAGE
mytestautofix   docker.io/sangeetha/myfirstacorn:v0.0.1*             21m ago     http://mywebnew-mytestautofix-a40c782d.local.oss-acorn.io   OK
```

Also spec filed has "autoUpgrade" set to true as expected.
```
acorn apps mytestautofix -o json | grep -i autoupgrade
                "autoUpgrade": true
                "observedAutoUpgrade": true,
```

Auto-upgrade gets triggered when new version of the image was made available as expected.
