### ISSUE TITLE
acorn run fails, complaining about DNS not resolving for beta.acorn.io

### ISSUE THREAD

**Issue by stevel032** [acorn-io/runtime#2317]
The "acorn run" command is failing for me today:

```
$ acorn run -n my-todo .
  ✗  ERROR:  Get "https://beta.acorn.io/apis/manager.acorn.io/v1/accounts/<my-uid>": dial tcp: lookup beta.acorn.io on 75.75.75.75:53: no such host
```

I was told that you guys have retired the beta.acorn.io, but I seem to have a local config file that points me in that direction:

```
$ cat config.yaml
acornConfig: /Users/<my-uid>/Library/Application Support/acorn/config.yaml
acornServers:
- beta.acorn.io
- acorn.io
auths:
  acorn.io:
    auth: xxx-yyy-xxx-yyy
  beta.acorn.io:
    auth: xxx-ooo-xxx-zzz
currentProject: beta.acorn.io/<my-uid>/acorn
defaultContext: beta.acorn.io/<my-uid>
```

This file seems to be created or modified only last week:

```
$ ls -ctl
total 8
-rw-r-xr-x  1 <my-uid>  staff  436 Oct 25 23:47 config.yaml
```

I am running the latest version:

```
$ brew upgrade acorn-io/cli/acorn
Warning: acorn-io/cli/acorn 0.9.1 already installed
```

Please advise the best way for me to get acorn running again. Thank you...

**Comment by thedadams** [comment]
@stevel032 Can you try the following in your terminal:
1. `acorn logout beta.acorn.io`
2. `acorn logout acorn.io`
3. `acorn login` and following the prompts, if necessary, to reconnect your CLI.

**Comment by stevel032** [comment]
Thank you, these instructions are very helpful, I'm up an running again!
