### ISSUE TITLE
promptOrder is not respected for secrets with credential type

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2386]
acorn version  - v0.10.0-rc1-7-g8b9acb47+8b9acb47

**Steps to reproduce the problem:**
1. Deploy app that has secrets with `promptOrder` 
```
secrets: config: {
	type: "credential.acorn.io/mytest"
	params: {
		promptOrder: ["proto", "address", "port", "adminUsername", "adminPassword", "username", "password"]
	}
	data: {
		address:       ""
		port:          ""
		username:      ""
		password:      ""
		adminUsername: ""
		adminPassword: ""
		proto:         ""
		dbName:        ""
	}
}
```
2. Following is the order in which I am prompted to enter data which is not respecting the `promptOrder` specified for the secrets:

```
mytestapp
STATUS: ENDPOINTS[] HEALTHY[] UPTODATE[] 
? address **
? adminPassword ***
? adminUsername ***
? dbName ***
? password ***
? port ***
? proto **
? username ***
```

**Expected Behavior:**
Order in which user is prompted should be the same as the  `promptOrder` specified for the secrets.

**Comment by cloudnautique** [comment]
Prompt order is now available on Main.

**Comment by sangee2004** [comment]
Tested with - acorn version - `v0.10.1-rc1-8-gce008aeb+ce008aeb`

User is promoted as per the prompt order for credential creation.
