### ISSUE TITLE
resolvedOfferings does not reflect the right value when memory override is done using "-m" option and when memory is also set for container in Acornfile.

### ISSUE THREAD

**Issue by sangee2004** [acorn-io/runtime#2415]
acorn version - `v0.10.0-rc2-9-g43dbcbf4+43dbcbf4`

**Steps to reproduce the problem:**
1. Deploy app  with memory override using "-m" option using Acornfile that has memory set for container in Acornfile  - ` acorn run -n test2 -m 128Mi .`

```
args: {
	newtext: "hello2"
	number:  1
	decimal: 1.1
}
containers: {
	mywebnew: {
		name:  "testweb1"
		image: "nginx"
		scale: 1
		ports: publish: "80/http"
		files: {
			"/usr/share/nginx/html/index.html": args.newtext
			"/usr/share/nginx/html/test.html":  "modified"
			"/usr/share/nginx/html/test1.html": "\(args.decimal)"
			"/usr/share/nginx/html/test2.html": "new1"
		}
                memory: 256Mi
	}
}
```
2. Once app is deployed , examine the `resolvedOfferings` field
```
                "resolvedOfferings": {
                    "containers": {
                        "": {
                            "class": "default",
                            "memory": 134217728,
                            "cpuScaler": 0.25
                        },
                        "mywebnew": {
                            "class": "default",
                            "memory": 268435456,
                            "cpuScaler": 0.25
                        }
                    },
                    "region": "acorn-sb-us-east-2"
                },
```

Resolved offerings shows the memory value set in  Acornfile for the containers.

**Expected Behavior:**
Resolved offerings should show the memory value set for the container from CLI which is what it gets deployed with.

**Comment by g-linville** [comment]
Just merged the fix. resolvedOfferings should look correct for the Acornfile given in this issue.

**Comment by sangee2004** [comment]
Tested with acorn version - `v0.10.0-rc2-17-g1142dab8+1142dab8`

Resolved offerings shows the right memory value set for the container from "-m" optioned used in the CLI as expected.
