### ISSUE TITLE
acorn dashboard - checking all the contexts and not working either

### ISSUE THREAD

**Issue by saiyam1814** [acorn-io/runtime#317]
This command actually tires to check against all the contexts in kubeconfig file. 
Ideally, it should only be the current context that it should be checked against. 
Has this been tested against 1.24? 
I have rancher desktop with 1.24 cluster and `acorn dashboard` gives an error.
<img width="1508" alt="Screenshot 2022-07-23 at 8 07 28 AM" src="https://user-images.githubusercontent.com/8190114/180587465-74e1ecc6-0196-4ebb-9d7c-76cd7483b476.png">

**Comment by cjellick** [comment]
We've removed the dashboard for now. Not sure how/when it will show up in the future. So, this issue will just remained parked for the time being.
