### ISSUE TITLE
Enhancement Request: Set DNS name within Acronfile

### ISSUE THREAD

**Issue by clemenko** [acorn-io/runtime#512]
It would be nice to be able to add a DNS name to the port definition of a container. 

something like
```
containers: {
    flask: {
        image: "clemenko/flask_simple"
        ports: publish: "flask.rfed.me:5000/http"
        scale: 1
    }
```

This will make shipping production apps a little more reproducible. Please allow for override from the command line with 
`-p flask.rfed.io:web:`

Similar to #206

**Comment by cjellick** [comment]
@ibuildthecloud I thought this would already be doable, no?

**Comment by ibuildthecloud** [comment]
There's a way to do this but you need an acorn of acorns.  I'll explain after the standup.  This stuff is undocumented, because again, on the fence about this stuff.

**Comment by ibuildthecloud** [comment]
Oh wait, there isn't.  Okay, let me think about how this can be done.
