### ISSUE TITLE
Support secret interpolation syntax

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#535]
Users want to achieve something lik:
```
files: "secret.txt": """
  verysecure = secret://my/secret
  """
```

Right now, you have to use secret templates, but that is more boilerplate than needed (see https://docs.acorn.io/authoring/secrets#template-secrets).

Have to decide on a syntax.

See acorn user slack: https://acorn-users.slack.com/archives/C03R9ME0SKC/p1660249028648629

**Comment by ibuildthecloud** [comment]
@cloudnautique This seems like it would simplify a lot of acorns you have built.

**Comment by cjellick** [comment]
so many iterations on this. just closing
