### ISSUE TITLE
job restart

### ISSUE THREAD

**Issue by cjellick** [acorn-io/runtime#831]

**Comment by sangee2004** [comment]
Tested with acorn version -  `v0.8.0-rc4-29-g6a019fe7+6a019fe7`

Able to list and get jobs using `acorn job` command for jobs with or without a schedule.

Able to validate the jobs in following states - `pending`, `running` , `failing` and `completed`.

There is an issue with tracking state of the job when restart is attempted which is tracked in https://github.com/acorn-io/runtime/issues/2092
