### ISSUE TITLE
Default to dash separated?

### ISSUE THREAD

**Issue by ibuildthecloud** [acorn-io/runtime#87]
container, job, secrets, acorns, etc keys have to be a-z0-9- because that is what k8s expects.  In general we were going to default all keys to camelCase but it's weird to save one key must be foo-bar and everything else is fooBar.  We should just ensure all keys are maybe foo-bar.  The crappy thing about dash separated is that you have to quote the key in cue.

**Comment by cloudnautique** [comment]
@cjellick were any fixes or changes to the code base done in this issue, or is it just to document the decission.

**Comment by cjellick** [comment]
I'm going to put this under the AML umbrella that @ibuildthecloud will be doing

**Comment by cjellick** [comment]
Moving out of v0.4.0, because I dont think @ibuildthecloud is going to get to it, given the kubecon release
